# Generated by Django 3.1.6 on 2021-03-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='number',
            new_name='number_of_people',
        ),
    ]
